💄 UI improvement in [View/details] page
likecoin/app-like-co pull request #131
Opened 2022-03-29 05:45 UTC by AuroraHuang22

- correct the version by fetching data from records data instead of metadata
- show file preview as long as the content type is image
- add progress indicator for loading preview image

2022-03-29 09:44 UTC, nwingt commented on pages/view/_iscnId.vue
> +    return this.record && this.record.data
TypeScript not working?

2022-03-29 09:44 UTC, nwingt commented on pages/view/_iscnId.vue
> +    return this.recordData.recordVersion
`recordData` may be undefined,

2022-03-29 09:46 UTC, nwingt requested changes

2022-03-29 09:46 UTC, nwingt commented on components/MetadataCard.vue
> +  isLoading: boolean = true
I suggest renaming this to more specify `hasLoadedImage`, with default is `false`

2022-03-30 03:35 UTC, AuroraHuang22 commented on pages/view/_iscnId.vue
> +    return this.record && this.record.data
After I re-run dev it works fine.

2022-04-06 06:17 UTC, williamchong approved these changes

2022-04-07 06:42 UTC, merged