💄 Update purchase UI
likecoin/app-like-co pull request #170
Opened 2022-07-27 16:21 UTC by AuroraHuang22

![截圖 2022-07-28 上午12 21 01](https://user-images.githubusercontent.com/75730405/181298614-44e3cbb0-5dfc-4b67-8e96-e25369c689be.png)

2022-07-27 16:37 UTC, williamchong requested changes
I think we still have many hardcode string without i18n but can handle later

2022-07-27 16:37 UTC, williamchong commented on pages/nft/iscn/_iscnId.vue
> +    if (!this.errorType && this.state === 'mint') return 'Mint NFT'
we don't need `!this.errorType` here since we have `if (this.errorType)` in front?

2022-07-27 16:37 UTC, williamchong commented on pages/nft/iscn/_iscnId.vue
> +    return `${LIKER_LAND_URL}/nft/class/${this.classId}`
Not sure if `classId` can contains anything that requires `encodeURIComponent`, safer to call it?

2022-07-27 16:37 UTC, williamchong commented on pages/nft/purchase/_iscnId.vue
> +    ]);
What should we show if one of these throw error? `this.$nuxt.error()`?

2022-07-27 16:37 UTC, williamchong commented on pages/nft/purchase/_iscnId.vue
> +            >Collect Now <template #prepend><IconPrice /></template
Wrap in `$t()`?

2022-07-28 06:15 UTC, williamchong approved these changes

2022-07-28 06:15 UTC, williamchong commented on pages/nft/iscn/_iscnId.vue
>            // TODO: use actual liker land class nft
Can remove now?

2022-07-28 06:40 UTC, nwingt commented on pages/nft/iscn/_iscnId.vue
> +      </Snackbar>
Indent not align?

2022-07-28 08:52 UTC, merged