✨ Update stakeholders @id no use did
likecoin/app-like-co pull request #179
Opened 2022-08-01 08:50 UTC by Tsai-Hsueh-Kuan

✨ Update stakeholders @id no use did

2022-08-01 09:57 UTC, williamchong requested changes

2022-08-01 09:57 UTC, williamchong commented on utils/cosmos/iscn/sign.ts
>          }
Just merge all 3 cases will do? Also please guard `propertyID` with `WALLET_TYPE_REPLACER[a.type] || a.type`

2022-08-02 07:15 UTC, williamchong approved these changes
@AuroraHuang22 Not sure about `id` and `address` prop use in the component, please comment

2022-08-02 07:48 UTC, williamchong approved these changes

2022-08-03 06:07 UTC, AuroraHuang22 approved these changes

2022-08-03 06:34 UTC, merged