Feat/stakeholder liker id refactor
likecoin/app-like-co pull request #215
Opened 2022-08-22 03:42 UTC by Tsai-Hsueh-Kuan

Feat/stakeholder liker id refactor

2022-08-22 17:34 UTC, williamchong requested changes

2022-08-22 17:34 UTC, williamchong commented on components/IscnRegisterForm.vue
> +  likerIdsAddress: string[] = []
```suggestion
  likerIdsAddresses: string[] = []
```

2022-08-22 17:34 UTC, williamchong commented on components/IscnRegisterForm.vue
> +          this.$axios.get(getLikerIdMinApi(e as string),
I think we should add .catch for each .get to prevent 1 invalid entry throwing all promises

2022-08-22 17:34 UTC, williamchong commented on components/IscnRegisterForm.vue
> +    } catch {
Please always add `console.error()` unless only an expected error would occur
Event if expected to be no-op, a console log is helpful if some unexpected error happen

2022-08-22 17:34 UTC, williamchong commented on pages/nft/url/index.vue
> +      likerIdsAddress: [],
```suggestion
      likerIdsAddresses: [],
```

2022-08-22 17:34 UTC, williamchong commented on utils/cosmos/iscn/iscn.type.ts
> +  likerIdsAddress: string[];
```suggestion
  likerIdsAddresses: string[];
```

2022-08-22 17:34 UTC, williamchong commented on utils/cosmos/iscn/sign.ts
> +        identifiers = likerIds.map((a: any) => ({
`likerId` should be added to `identifiers` if it exists and is valid, no matter if previously `identifiers` exists or not

2022-08-22 17:34 UTC, williamchong commented on utils/cosmos/iscn/sign.ts
> +            '@id': identifiers.length ? identifiers[0].value : likerIdsAddress[i] || url,
Confusing code here, I think we should just store `wallet` as a variable and use `wallet || url` here

2022-08-24 08:41 UTC, williamchong commented on utils/cosmos/iscn/sign.ts
> +      const likerIdentifiers:any = likerIds.map((a: any) => ({
Should this be `likerIds[i]` or `likerIds.map()`? Not sure the original meaning for `likerIds` but seems url is `likerIds[i]`

2022-08-24 08:41 UTC, williamchong commented on components/IscnRegisterForm.vue
> +          .then((element):any => element?.data?.likeWallet)
I think the type should be `AxiosResponse`

2022-08-25 10:46 UTC, WeiJun0827 approved these changes

2022-08-25 10:50 UTC, merged