💄 [nft/_iscnId] Add Writing NFT Preview Card
likecoin/app-like-co pull request #250
Opened 2022-10-16 09:08 UTC by AuroraHuang22

![截圖 2022-10-16 下午4 39 50](https://user-images.githubusercontent.com/75730405/196027424-2ecbf03a-6971-48d5-af33-1efbf0396205.png)

2022-10-16 17:53 UTC, williamchong commented on components/NFTPreviewCard.vue
> +        <img id="imgElement" alt="og image" src="" />
Why not use prop or ref?

2022-10-17 09:18 UTC, williamchong requested changes

2022-10-17 09:18 UTC, williamchong commented on pages/nft/iscn/_iscnId.vue
> +      this.imgSrc = objectURL
So `imgSrc` can be a `computed` base on `this.ogImageBlob`?

2022-10-18 05:00 UTC, nwingt commented on components/icon/Eye.vue
> +    height="14"
Should be a square?

2022-10-18 22:23 UTC, williamchong approved these changes

2022-10-19 07:30 UTC, nwingt commented on components/icon/Eye.vue
>      viewBox="0 0 20 14"
Should change viewBox and path too I suppose

2022-10-19 10:28 UTC, nwingt approved these changes

2022-10-19 10:38 UTC, merged