♻️ Refactor tag & Remove placeholder
likecoin/app-like-co pull request #27
Opened 2021-08-18 11:00 UTC by AuroraHuang22

- [ ] 改動 `uploadForm` 的 `input accept type` 也沒辦法順利上傳 image 以外的檔案，先跳過

2021-08-18 11:01 UTC, AuroraHuang22 commented on components/IscnRegisterForm.vue
> +            <!-- <div class="font-semibold">
錢包只找到 id 找不到名字，忍痛跳過

2021-08-18 11:02 UTC, AuroraHuang22 commented on components/IscnRegisterForm.vue
> +            </div> -->
只找到錢包的 ID 找不到名字，忍痛跳過

2021-08-18 11:10 UTC, nwingt requested changes

2021-08-18 11:10 UTC, nwingt commented on components/IscnUploadedInfo.vue
> +  @Prop() readonly playload!: any
payload?

2021-08-18 11:10 UTC, nwingt commented on components/IscnUploadedInfo.vue
> +        {{ descript }}
description

2021-08-18 11:10 UTC, nwingt commented on components/IscnUploadedInfo.vue
> +      this.records[this.records.length - 1].data.contentMetadata.description
```suggestion
   const { title, description } =
      this.records[this.records.length - 1].data.contentMetadata

this.title = title
this.description = description
```

2021-08-18 11:12 UTC, AuroraHuang22 commented on components/IscnUploadedInfo.vue
> +  @Prop() readonly playload!: any
誤打 🤦‍♀️

2021-08-19 02:05 UTC, AuroraHuang22 commented on components/SearchResults.vue
> +            {{ record.data.contentMetadata.name || record.data.contentMetadata.title }}
之前註冊的內容沒有 name 可以顯示

2021-08-19 02:38 UTC, nwingt requested changes

2021-08-19 02:38 UTC, nwingt commented on components/UploadForm.vue
> +      this.fileSize= files[0].size
```suggestion
      this.fileName = files[0].name
      this.fileSize = files[0].size
```

2021-08-19 02:38 UTC, nwingt commented on components/SearchResults.vue
> +          />
我建議把每個 SearchResult 都變成一個 component

2021-08-19 03:18 UTC, nwingt requested changes

2021-08-19 03:18 UTC, nwingt commented on components/SearchResult.vue
> +  <div class="w-min mx-[12px] mb-[48px]">
如果是用 Grid，不需要在子 Component 加上 margin
在 Grid 加 [gap](https://tailwindcss.com/docs/gap) 更方便

2021-08-19 03:18 UTC, nwingt commented on components/SearchResult.vue
> +      }}
可以用 getter

2021-08-19 03:18 UTC, nwingt commented on components/SearchResult.vue
> +      record.data.contentMetadata.keywords.split(',')"
可以用 getter 簡化

2021-08-19 03:18 UTC, nwingt commented on components/UploadForm.vue
> +  }
```suggestion
  get size() {
    return Math.round(this.fileSize * 0.001)
  }
```

2021-08-19 04:03 UTC, nwingt requested changes

2021-08-19 04:03 UTC, nwingt commented on components/SearchResult.vue
> +  }
```suggestion
  get keywords(): Array<string> {
    return this.data.keywords ? this.data.keywords.split(',') : []
  }

2021-08-19 04:03 UTC, nwingt commented on components/SearchResults.vue
> +        <SearchResult :data="record.data.contentMetadata" />
I prefer to inject a `record` instead of data

2021-08-19 04:22 UTC, nwingt commented on pages/view/_iscnId.vue
> +  get keywords(): Array<String> {
```suggestion
  get keywords(): Array<string> {
```

2021-08-19 04:25 UTC, nwingt approved these changes

2021-08-19 04:26 UTC, merged