🐛 retrieve stakeholder info from stakeholders.entity
likecoin/app-like-co pull request #32
Opened 2021-08-20 14:58 UTC by AuroraHuang22

2021-08-20 15:04 UTC, nwingt commented on components/StakeholderInfo.vue
> +      </div>
What is the for?

2021-08-22 14:12 UTC, williamchong requested changes

2021-08-22 14:12 UTC, williamchong commented on utils/cosmos/iscn/sign.ts
> +      const isNonEmpty = authorUrl || authorName
Any one of the author field exists then it should be isNonEmpty

2021-08-22 14:12 UTC, williamchong commented on utils/cosmos/iscn/sign.ts
> +                '@id': `did:cosmos:${authorId.slice(6)}` || undefined,
id should not be left as empty
if wallet not exists, use url
if wallet nor url exists, use name as id

2021-08-22 15:59 UTC, williamchong approved these changes

2021-08-23 02:25 UTC, nwingt requested changes

2021-08-23 02:25 UTC, nwingt commented on components/StakeholderInfo.vue
> +  }
Prefer not use isXXXX for non boolean
```suggestion
  get walletAddress() {
    if (this.id && this.id.includes('cosmos')) {
      return `cosmos${this.id.slice(11)}`
    }
    return ''
  }
```

2021-08-23 03:05 UTC, merged