🐛 Remove unnecessary Link tag
likecoin/app-like-co pull request #341
Opened 2023-04-21 18:26 UTC by AuroraHuang22

- Before

<img width="710" alt="截圖 2023-04-22 上午2 25 45" src="https://user-images.githubusercontent.com/75730405/233708943-640cc9f3-1026-44d9-b99a-2ac1db4c8530.png">

2023-04-21 18:30 UTC, williamchong requested changes

2023-04-21 18:30 UTC, williamchong commented on pages/view/_iscnId.vue
> +            {{ metadata.usageInfo }}
usageInfo can be a url, we should check if it is an url and use link tag, otherwise this patch makes sense

2023-04-22 00:59 UTC, ckxpress commented
does it mean i can put "https://creativecommons.org/licenses/by-nc-sa/4.0/" in usageInfo field in iscn.json and have it correctly displayed?

2023-04-22 01:30 UTC, williamchong approved these changes
Probably a simple startsWith() is sufficient though

2023-04-22 05:18 UTC, nwingt approved these changes

2023-04-22 05:20 UTC, nwingt commented on pages/view/_iscnId.vue
> +              v-if="urlPattern.test(metadata.usageInfo)"
make this as a computed prop, then you don't have to inject `URL_REGEX` into data

2023-04-22 10:04 UTC, williamchong requested changes

2023-04-22 10:04 UTC, williamchong commented on pages/view/_iscnId.vue
> +  get isValidUrl() {
```suggestion
  get isUsageInfoUrl() {
```

2023-04-22 10:04 UTC, williamchong commented on pages/view/_iscnId.vue
> +              v-if="isValidUrl"
```suggestion
              v-if="isUsageInfoUrl"
```

2023-04-22 10:06 UTC, williamchong requested changes

2023-04-22 10:06 UTC, williamchong commented on pages/view/_iscnId.vue
> +      this.metadata.usageInfo.startsWith('ftp://')
Should check if `this.metadata` and `this.metadata.usageInfo` exists
i.e
```
      this.metadata?.usageInfo && (
      this.metadata.usageInfo.startsWith('http://') ||
      this.metadata.usageInfo.startsWith('https://') ||
      this.metadata.usageInfo.startsWith('ftp://'))
```
Not sure if this is valid syntax, please try

2023-04-22 13:55 UTC, williamchong approved these changes

2023-04-22 17:40 UTC, merged