✨ Add feature to estimate registration fee with lodash debounce
likecoin/app-like-co pull request #38
Opened 2021-08-27 03:05 UTC by AuroraHuang22

2021-08-30 03:15 UTC, nwingt approved these changes

2021-08-30 03:15 UTC, nwingt commented
@williamchong Please help to review

2021-08-30 12:40 UTC, williamchong requested changes

2021-08-30 12:40 UTC, williamchong commented on components/IscnRegisterForm.vue
> +  @Watch('authorWallets')
Why not just deep watch `this.payload` instead?

2021-08-31 06:26 UTC, nwingt approved these changes

2021-08-31 08:31 UTC, williamchong approved these changes

2021-09-01 02:31 UTC, merged