✨ Support uploading multiple files
likecoin/app-like-co pull request #400
Opened 2023-10-25 02:24 UTC by AuroraHuang22

2023-10-27 15:47 UTC, williamchong requested changes

2023-10-27 15:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +      </FormField> -->
Please keep this checkbox, tick means upload all files to number, none means not

2023-10-27 15:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +  formattedArweave(arweaveId: string) {
method should be verb. e.g. `formatIpfs` and `formatArweave`

2023-10-27 15:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +      this.uploadArweaveIdList.push(this.arweaveId)
Should reset `this.uploadArweaveIdList`? ie `this.uploadArweaveIdList = [this.arweaveId]`

2023-10-27 15:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +        }
Should check and call `submitToNumbers`

2023-10-27 15:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +     tempRecord.transactionHash = await this.sendArweaveFeeTx(tempRecord);
Should also check if file is already uploaded and has a arweave Id

2023-10-27 15:47 UTC, williamchong commented on utils/cosmos/iscn/iscn.type.ts
> +  fileSHA256: any;
Please use `string[]` if we are using array only, `string | string[]` if either are possible

2023-10-27 15:47 UTC, williamchong commented on pages/new/index.vue
> +        ipfsHash:this.urlIpfsHash,
Please fix indent and spaces

2023-10-27 15:47 UTC, williamchong commented on pages/new/index.vue
> +        this.urlFileRecords.push({
Should reset `this.urlFileRecords`

2023-10-27 15:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +        this.uploadArweaveIdList.push(arweaveId)
Save the arweave Id back to `tempRecord` in case we will retry the whole batch

2023-10-29 07:38 UTC, AuroraHuang22 commented on pages/nft/url/index.vue
> +      exifInfo: [],
oops .. should be an object

2023-10-30 03:47 UTC, williamchong commented on components/IscnRegisterForm.vue
> +  sentArweaveTransactionHashes = new Map<string, any>()
if we already know it the `any` is a object with 2 optional key `transactionHash` and `arweaveId` we might as well define it

2023-10-30 04:03 UTC, williamchong approved these changes

2023-10-30 09:07 UTC, merged