[TAS-918] 🚸 Add iscnOwner to stakeholders
likecoin/app-like-co pull request #435
Opened 2024-01-09 12:39 UTC by AuroraHuang22

![截圖 2024-01-09 晚上8 26 35](https://github.com/likecoin/app-like-co/assets/75730405/4e844fb8-88c4-4441-91ad-5c7186d53c43)
![截圖 2024-01-09 晚上8 26 45](https://github.com/likecoin/app-like-co/assets/75730405/33de9be1-570b-48bf-a5c6-cf7ef8a61d7e)

2024-01-09 16:01 UTC, williamchong commented on components/IscnRegisterForm.vue
> +        content: 'like1qv66yzpgg9f8w46zj7gkuk9wd2nrpqmca3huxf',
```suggestion
        content: this.address,
```

2024-01-09 16:20 UTC, AuroraHuang22 commented on components/IscnRegisterForm.vue
> +        content: 'like1qv66yzpgg9f8w46zj7gkuk9wd2nrpqmca3huxf',
😅 updated

2024-01-09 16:35 UTC, williamchong requested changes
Please keep array type if wallet must be array of object

2024-01-09 16:35 UTC, williamchong commented on components/IscnRegisterForm.vue
> +  authorWalletAddress: any = []
```suggestion
  authorWalletAddress: any[] = []
```

2024-01-09 16:35 UTC, williamchong commented on types/author.d.ts
> +  wallet: any;
```suggestion
  wallet: any[];
```

2024-01-10 01:33 UTC, AuroraHuang22 commented on components/IscnRegisterForm.vue
> +  authorWalletAddress: any = []
[4d26903](https://github.com/likecoin/app-like-co/pull/435/commits/4d26903c8f4d854ec1fbc8866d04ea7777122717)

2024-01-10 01:59 UTC, williamchong approved these changes

2024-01-10 05:48 UTC, merged