✨ Add LIKE tx for arweave fee feature
likecoin/app-like-co pull request #48
Opened 2021-09-14 17:43 UTC by williamchong

2021-09-20 02:34 UTC, nwingt requested changes

2021-09-20 02:34 UTC, nwingt commented on components/IscnRegisterForm.vue
> +  chang(newId: string) {
```suggestion
  handleUploadArweaveIDChange(newId: string) {
```

2021-09-20 02:34 UTC, nwingt commented on components/IscnRegisterForm.vue
> +    // Total Fee needs Arweave fee to calculate
```suggestion
    // ISCN Fee needs Arweave fee to calculate
```

2021-09-20 02:34 UTC, nwingt commented on components/IscnRegisterForm.vue
> +      console.error(err);
```suggestion
      // TODO: Handle error
      console.error(err);
```

2021-09-20 02:34 UTC, nwingt commented on components/IscnRegisterForm.vue
> +    this.uploadStatus = 'Waiting for signature'
Should localize

2021-09-20 02:34 UTC, nwingt commented on components/IscnRegisterForm.vue
> +      console.error(err);
```suggestion
      // TODO: Handle error
      console.error(err);
```

2021-09-20 02:34 UTC, nwingt commented on server/arweave/index.ts
> +export async function converARPriceToLIKE(ar: string, { margin = 0.05, decimal = 0 } = {}) {
```suggestion
export async function convertARPriceToLIKE(ar: string, { margin = 0.05, decimal = 0 } = {}) {
```

2021-09-20 02:34 UTC, nwingt commented on server/arweave/router.ts
> +    const LIKE = await converARPriceToLIKE(AR);
```suggestion
    const LIKE = await convertARPriceToLIKE(AR);
```

2021-09-23 01:26 UTC, nwingt commented
Please rebase likecoin:feature/arweave to likecoin:master

2021-09-23 05:20 UTC, williamchong commented
Since the first branch out rebase would cause too many conflicts, so I had been using merge

2021-09-23 06:20 UTC, merged